name: main
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VSIX_FILE: r-debugger.vsix
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: lannonbr/vsce-action@master
        with:
          args: "package -o $VSIX_FILE"
      - uses: actions/upload-artifact@v1
        with:
          name: ${{ env.VSIX_FILE }}
          path: ${{ env.VSIX_FILE }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - run: npm install
      - run: npm run lint
